CART_TOKEN_HEADER = "X-Cart-Token"
CART_TOKEN_QUERY_PARAM = "cart_token"

SETTING_OTP_EXPIRE_MINUTES = "OTP_EXPIRE_MINUTES"
SETTING_MIN_ORDER_AMOUNT = "MIN_ORDER_AMOUNT"
SETTING_DEFAULT_FROM_EMAIL = "DEFAULT_FROM_EMAIL"

DEFAULT_OTP_EXPIRE_MINUTES = 15
DEFAULT_MIN_ORDER_AMOUNT = "0"
DEFAULT_FROM_EMAIL = "noreply@example.com"
