# Generated by Django 6.0.1 on 2026-02-03 10:22

import django.db.models.deletion
from django.db import migrations, models


def migrate_product_images(apps, schema_editor):
    Product = apps.get_model("shop", "Product")
    ProductImage = apps.get_model("shop", "ProductImage")
    for product in Product.objects.all():
        if product.image:
            ProductImage.objects.create(
                product=product,
                image=product.image,
                is_cover=True,
                order=0,
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_add_email_change_and_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'db_table': 'shop_productimage',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(migrate_product_images, noop),
    ]
